const trips = [
    {
        id:1,
        name: "Cat Chain",
        price: "18,99 €",
        date: "16.07.2019",
        score: 4.5,
        supplier: 'Aliexpress',
        distance: '38 km',
        from: 'Leverkusen Rheindorf',
        to: 'Köln-Mülheim',
    },
    {
        id:2,
        name: "Batman Tshirt",
        price: "0,99 €",
        date: "17.07.2019",
        score: 2.5,
        supplier: 'Amazon',
        distance: '13 km',
        from: 'Köln-Porz',
        to: 'Köln-Buchforst',
    },
    {
        id:3,
        name: "Cup Accesoire",
        price: "22,99 €",
        date: "18.07.2019",
        score: 5,
        supplier: 'Alibaba',
        distance: '19 km',
        from: 'Düsseldorf Hbf',
        to: 'Köln Hbf',
    },
    {
        id:4,
        name: "Cat Chain",
        price: "18,99 €",
        date: "16.07.2019",
        score: 4.5,
        supplier: 'Aliexpress',
        distance: '38 km',
        from: 'Leverkusen Rheindorf',
        to: 'Köln-Mülheim',
    },
    {
        id:5,
        name: "Batman Tshirt",
        price: "0,99 €",
        date: "17.07.2019",
        score: 2.5,
        supplier: 'Amazon',
        distance: '13 km',
        from: 'Köln-Porz',
        to: 'Köln-Buchforst',
    },
    {
        id:6,
        name: "Cup Accesoire",
        price: "22,99 €",
        date: "18.07.2019",
        score: 5,
        supplier: 'Alibaba',
        distance: '19 km',
        from: 'Düsseldorf Hbf',
        to: 'Köln Hbf',
    },
    {
        id:7,
        name: "Cat Chain",
        price: "18,99 €",
        date: "16.07.2019",
        score: 4.5,
        supplier: 'Aliexpress',
        distance: '38 km',
        from: 'Leverkusen Rheindorf',
        to: 'Köln-Mülheim',
    },
    {
        id:8,
        name: "Batman Tshirt",
        price: "0,99 €",
        date: "17.07.2019",
        score: 2.5,
        supplier: 'Amazon',
        distance: '13 km',
        from: 'Köln-Porz',
        to: 'Köln-Buchforst',
    },
    {
        id:9,
        name: "Cup Accesoire",
        price: "22,99 €",
        date: "18.07.2019",
        score: 5,
        supplier: 'Alibaba',
        distance: '19 km',
        from: 'Düsseldorf Hbf',
        to: 'Köln Hbf',
    },
    {
        id:10,
        name: "Cat Chain",
        price: "18,99 €",
        date: "16.07.2019",
        score: 4.5,
        supplier: 'Aliexpress',
        distance: '38 km',
        from: 'Leverkusen Rheindorf',
        to: 'Köln-Mülheim',
    },
    {
        id:11,
        name: "Batman Tshirt",
        price: "0,99 €",
        date: "17.07.2019",
        score: 2.5,
        supplier: 'Amazon',
        distance: '13 km',
        from: 'Köln-Porz',
        to: 'Köln-Buchforst',
    },
    {
        id:12,
        name: "Cup Accesoire",
        price: "22,99 €",
        date: "18.07.2019",
        score: 5,
        supplier: 'Alibaba',
        distance: '19 km',
        from: 'Düsseldorf Hbf',
        to: 'Köln Hbf',
    },
];

export { trips };